# This file defines services for deployment on Render.com
# It tells Render how to build and run the application

services:
  - type: web
    name: resume-api
    runtime: python
    buildCommand: |
    "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
