# This file defines services for deployment on Render.com
# It tells Render how to build and run the application

services:
  - type: web
    name: resume-api
    runtime: python
    buildCommand: |
    "pip install -r requirements.txt"
    "python generate_train/generate_data.py"
    "python generate_train/train_model.py"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000